colang_version: "1.0"

# models:
#   - type: main
#     engine: openai
#     model: llama3.2:latest

rails:
  input:
    flows:
      - check_dangerous_content
      - check_code_content
      - check_unrelated_content